[profile.release]
debug = true

[workspace]
members = [
  "components/airlock",
  "components/builder-api",
  "components/builder-core",
  "components/builder-db",
  "components/builder-depot",
  "components/builder-graph",
  "components/builder-http-gateway",
  "components/builder-jobsrv",
  "components/builder-originsrv",
  "components/builder-protocol",
  "components/builder-router",
  "components/builder-sessionsrv",
  "components/builder-worker",
  "components/net",
  "components/op"
]

[patch."https://github.com/habitat-sh/core.git"]
habitat_core = {path = "/src/core/components/core"}
habitat_win_users = {path = "/src/core/components/win-users"}